POST {{protocol}}{{host}}/user/add
Content-Type: application/json

{
  "username": "szhdqwu12`",
  "password": "159798753",
  "userType": 1,
  "roleIds": [3]
}

###  修改用户
PUT  {{protocol}}{{host}}/user/edit/1
Content-Type: application/json

{
  "username": "宋志恒123",
  "password": "134564",
  "userType": 1,
  "roleIds": [2]
}

###  删除用户
DELETE  {{protocol}}{{host}}/user/12

###  获取用户
GET  {{protocol}}{{host}}/user/4