POST {{protocol}}{{host}}/user/add
Content-Type: application/json

{
  "username": "szh123",
  "password": "159753",
  "userType": 1
}

###  修改用户
PUT  {{protocol}}{{host}}/user/edit


###  删除用户
DELETE  {{protocol}}{{host}}/user/3